export const ESTATEPLAN_LIST_REQUEST = "ESTATEPLAN_LIST_REQUEST";
export const ESTATEPLAN_LIST_SUCCESS = "ESTATEPLAN_LIST_SUCCESS";
export const ESTATEPLAN_LIST_FAIL = "ESTATEPLAN_LIST_FAIL";

export const ESTATEPLAN_DETAILS_REQUEST = "ESTATEPLAN_DETAILS_REQUEST";
export const ESTATEPLAN_DETAILS_SUCCESS = "ESTATEPLAN_DETAILS_SUCCESS";
export const ESTATEPLAN_DETAILS_FAIL = "ESTATEPLAN_DETAILS_FAIL";

export const ESTATEPLAN_EDIT_REQUEST = "ESTATEPLAN_EDIT_REQUEST";
export const ESTATEPLAN_EDIT_SUCCESS = "ESTATEPLAN_EDIT_SUCCESS";
export const ESTATEPLAN_EDIT_FAIL = "ESTATEPLAN_EDIT_FAIL";

export const ESTATEPLAN_SAVE_REQUEST = "ESTATEPLAN_SAVE_REQUEST";
export const ESTATEPLAN_SAVE_SUCCESS = "ESTATEPLAN_SAVE_SUCCESS";
export const ESTATEPLAN_SAVE_FAIL = "ESTATEPLAN_SAVE_FAIL";

export const ESTATEPLAN_DELETE_REQUEST = "ESTATEPLAN_DELETE_REQUEST";
export const ESTATEPLAN_DELETE_SUCCESS = "ESTATEPLAN_DELETE_SUCCESS";
export const ESTATEPLAN_DELETE_FAIL = "ESTATEPLAN_DELETE_FAIL";
